"""add nm_id cpm avg_pos atbs shks to ad_search_clusters

Revision ID: 07466f417291
Revises: 8ead52702fbd
Create Date: 2026-06-15 21:50:29.254096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07466f417291'
down_revision: Union[str, Sequence[str], None] = '8ead52702fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_search_clusters', sa.Column('nm_id', sa.Integer(), nullable=True))
    op.add_column('ad_search_clusters', sa.Column('cpm', sa.Float(), nullable=False))
    op.add_column('ad_search_clusters', sa.Column('avg_pos', sa.Float(), nullable=False))
    op.add_column('ad_search_clusters', sa.Column('atbs', sa.Integer(), nullable=False))
    op.add_column('ad_search_clusters', sa.Column('shks', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_ad_search_cluster'), 'ad_search_clusters', type_='unique')
    op.create_unique_constraint('uq_ad_search_cluster', 'ad_search_clusters', ['cabinet_id', 'advert_id', 'nm_id', 'keyword'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ad_search_cluster', 'ad_search_clusters', type_='unique')
    op.create_unique_constraint(op.f('uq_ad_search_cluster'), 'ad_search_clusters', ['cabinet_id', 'advert_id', 'keyword'])
    op.drop_column('ad_search_clusters', 'shks')
    op.drop_column('ad_search_clusters', 'atbs')
    op.drop_column('ad_search_clusters', 'avg_pos')
    op.drop_column('ad_search_clusters', 'cpm')
    op.drop_column('ad_search_clusters', 'nm_id')
    # ### end Alembic commands ###
