"""add ad_search_clusters table

Revision ID: 8ead52702fbd
Revises: eb7bdbb26cde
Create Date: 2026-06-14 16:27:09.856490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ead52702fbd'
down_revision: Union[str, Sequence[str], None] = 'eb7bdbb26cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_search_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.String(length=32), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('bids', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('cpc', sa.Float(), nullable=False),
    sa.Column('sum_price', sa.Float(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cabinet_id', 'advert_id', 'keyword', name='uq_ad_search_cluster')
    )
    op.create_index(op.f('ix_ad_search_clusters_advert_id'), 'ad_search_clusters', ['advert_id'], unique=False)
    op.create_index(op.f('ix_ad_search_clusters_cabinet_id'), 'ad_search_clusters', ['cabinet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_search_clusters_cabinet_id'), table_name='ad_search_clusters')
    op.drop_index(op.f('ix_ad_search_clusters_advert_id'), table_name='ad_search_clusters')
    op.drop_table('ad_search_clusters')
    # ### end Alembic commands ###
