"""recreate_analytics_tables_for_v2_stocks_report

Revision ID: b9bef58c9f87
Revises: c3d4e5f6a7b8
Create Date: 2026-06-13 19:42:22.287927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9bef58c9f87'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_metrics', sa.Column('vendor_code', sa.String(length=200), nullable=True))
    op.add_column('funnel_metrics', sa.Column('product_name', sa.String(length=500), nullable=True))
    op.add_column('funnel_metrics', sa.Column('avg_orders', sa.Float(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('avg_orders_month1', sa.Float(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('avg_orders_month2', sa.Float(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('buyout_percent', sa.Float(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_order_buyout', sa.Float(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('sale_rate_days', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('stock_turnover_days', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('availability', sa.String(length=50), nullable=True))
    op.alter_column('funnel_metrics', 'period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('funnel_metrics', 'period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('funnel_metrics', 'conv_cart_order',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('funnel_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_funnel_metrics_date'), table_name='funnel_metrics')
    op.drop_constraint(op.f('uq_funnel_metric'), 'funnel_metrics', type_='unique')
    op.create_unique_constraint('uq_funnel_metric', 'funnel_metrics', ['cabinet_id', 'nm_id', 'period_start', 'period_end'])
    op.create_index(op.f('ix_funnel_metrics_period_start'), 'funnel_metrics', ['period_start'], unique=False)
    op.drop_column('funnel_metrics', 'views')
    op.drop_column('funnel_metrics', 'conv_view_sale')
    op.drop_column('funnel_metrics', 'sa_name')
    op.drop_column('funnel_metrics', 'conv_order_sale')
    op.drop_column('funnel_metrics', 'date')
    op.drop_column('funnel_metrics', 'cart_adds')
    op.drop_column('funnel_metrics', 'returns_count')
    op.drop_column('funnel_metrics', 'revenue')
    op.drop_column('funnel_metrics', 'orders_count')
    op.drop_column('funnel_metrics', 'purchased')
    op.drop_column('funnel_metrics', 'conv_view_cart')
    op.drop_index(op.f('idx_orders_date'), table_name='orders')
    op.add_column('shelf_metrics', sa.Column('vendor_code', sa.String(length=200), nullable=True))
    op.add_column('shelf_metrics', sa.Column('product_name', sa.String(length=500), nullable=True))
    op.add_column('shelf_metrics', sa.Column('main_photo', sa.String(length=500), nullable=True))
    op.add_column('shelf_metrics', sa.Column('orders_sum', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('avg_orders', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('buyout_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('buyout_sum', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('buyout_percent', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('stock_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('stock_sum', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('sale_rate_days', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('to_client_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('from_client_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_orders_count', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_orders_sum', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_buyouts_count', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_buyouts_sum', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('availability', sa.String(length=50), nullable=True))
    op.alter_column('shelf_metrics', 'period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_metrics', 'period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shelf_metrics', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('shelf_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_shelf_metrics_date'), table_name='shelf_metrics')
    op.drop_constraint(op.f('uq_shelf_metric'), 'shelf_metrics', type_='unique')
    op.create_unique_constraint('uq_shelf_metric', 'shelf_metrics', ['cabinet_id', 'nm_id', 'period_start', 'period_end'])
    op.create_index(op.f('ix_shelf_metrics_period_start'), 'shelf_metrics', ['period_start'], unique=False)
    op.drop_column('shelf_metrics', 'open_card')
    op.drop_column('shelf_metrics', 'views')
    op.drop_column('shelf_metrics', 'sa_name')
    op.drop_column('shelf_metrics', 'date')
    op.drop_column('shelf_metrics', 'orders_wb')
    op.drop_column('shelf_metrics', 'conversion_tobuy')
    op.drop_column('shelf_metrics', 'cart_adds')
    op.drop_column('shelf_metrics', 'returns_count')
    op.drop_column('shelf_metrics', 'revenue')
    op.drop_column('shelf_metrics', 'barcode')
    op.drop_column('shelf_metrics', 'added_to_cart')
    op.drop_column('shelf_metrics', 'purchased')
    op.drop_column('shelf_metrics', 'conversion_tocart')
    op.alter_column('wb_tokens', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wb_tokens', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('shelf_metrics', sa.Column('conversion_tocart', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('purchased', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('added_to_cart', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('returns_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('cart_adds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('conversion_tobuy', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('orders_wb', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('sa_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('open_card', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shelf_metrics_period_start'), table_name='shelf_metrics')
    op.drop_constraint('uq_shelf_metric', 'shelf_metrics', type_='unique')
    op.create_unique_constraint(op.f('uq_shelf_metric'), 'shelf_metrics', ['cabinet_id', 'nm_id', 'date'])
    op.create_index(op.f('ix_shelf_metrics_date'), 'shelf_metrics', ['date'], unique=False)
    op.alter_column('shelf_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shelf_metrics', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shelf_metrics', 'period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shelf_metrics', 'period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('shelf_metrics', 'availability')
    op.drop_column('shelf_metrics', 'lost_buyouts_sum')
    op.drop_column('shelf_metrics', 'lost_buyouts_count')
    op.drop_column('shelf_metrics', 'lost_orders_sum')
    op.drop_column('shelf_metrics', 'lost_orders_count')
    op.drop_column('shelf_metrics', 'from_client_count')
    op.drop_column('shelf_metrics', 'to_client_count')
    op.drop_column('shelf_metrics', 'sale_rate_days')
    op.drop_column('shelf_metrics', 'stock_sum')
    op.drop_column('shelf_metrics', 'stock_count')
    op.drop_column('shelf_metrics', 'buyout_percent')
    op.drop_column('shelf_metrics', 'buyout_sum')
    op.drop_column('shelf_metrics', 'buyout_count')
    op.drop_column('shelf_metrics', 'avg_orders')
    op.drop_column('shelf_metrics', 'orders_sum')
    op.drop_column('shelf_metrics', 'main_photo')
    op.drop_column('shelf_metrics', 'product_name')
    op.drop_column('shelf_metrics', 'vendor_code')
    op.create_index(op.f('idx_orders_date'), 'orders', [sa.literal_column('date DESC')], unique=False)
    op.add_column('funnel_metrics', sa.Column('conv_view_cart', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('purchased', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('orders_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('returns_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('cart_adds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_order_sale', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('sa_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('conv_view_sale', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_funnel_metrics_period_start'), table_name='funnel_metrics')
    op.drop_constraint('uq_funnel_metric', 'funnel_metrics', type_='unique')
    op.create_unique_constraint(op.f('uq_funnel_metric'), 'funnel_metrics', ['cabinet_id', 'nm_id', 'date'])
    op.create_index(op.f('ix_funnel_metrics_date'), 'funnel_metrics', ['date'], unique=False)
    op.alter_column('funnel_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('funnel_metrics', 'conv_cart_order',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('funnel_metrics', 'period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('funnel_metrics', 'period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('funnel_metrics', 'availability')
    op.drop_column('funnel_metrics', 'stock_turnover_days')
    op.drop_column('funnel_metrics', 'sale_rate_days')
    op.drop_column('funnel_metrics', 'conv_order_buyout')
    op.drop_column('funnel_metrics', 'buyout_percent')
    op.drop_column('funnel_metrics', 'avg_orders_month2')
    op.drop_column('funnel_metrics', 'avg_orders_month1')
    op.drop_column('funnel_metrics', 'avg_orders')
    op.drop_column('funnel_metrics', 'product_name')
    op.drop_column('funnel_metrics', 'vendor_code')
    # ### end Alembic commands ###
