"""add claims, warehouses, tariffs tables

Revision ID: c8f4a385cbb6
Revises: fc5600d6ee37
Create Date: 2026-06-20 12:49:06.804390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f4a385cbb6'
down_revision: Union[str, Sequence[str], None] = 'fc5600d6ee37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('srid', sa.String(length=100), nullable=True),
    sa.Column('imt_name', sa.String(length=500), nullable=True),
    sa.Column('claim_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('status_ex', sa.Integer(), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('wb_comment', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('order_dt', sa.DateTime(), nullable=True),
    sa.Column('dt_update', sa.DateTime(), nullable=True),
    sa.Column('delivery_dt', sa.DateTime(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('video_paths', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cabinet_id', 'claim_id', name='uq_claim')
    )
    op.create_index(op.f('ix_claims_cabinet_id'), 'claims', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_claims_nm_id'), 'claims', ['nm_id'], unique=False)
    op.create_index(op.f('ix_claims_srid'), 'claims', ['srid'], unique=False)
    op.create_table('tariff_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('allow_unload', sa.Boolean(), nullable=False),
    sa.Column('box_type_id', sa.Integer(), nullable=False),
    sa.Column('is_sorting_center', sa.Boolean(), nullable=False),
    sa.Column('storage_coef', sa.String(length=50), nullable=True),
    sa.Column('delivery_coef', sa.String(length=50), nullable=True),
    sa.Column('delivery_base_liter', sa.String(length=50), nullable=True),
    sa.Column('delivery_additional_liter', sa.String(length=50), nullable=True),
    sa.Column('storage_base_liter', sa.String(length=50), nullable=True),
    sa.Column('storage_additional_liter', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'date', 'box_type_id', name='uq_tariff_acceptance')
    )
    op.create_index(op.f('ix_tariff_acceptances_warehouse_id'), 'tariff_acceptances', ['warehouse_id'], unique=False)
    op.create_table('tariff_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('geo_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_coef', sa.String(length=50), nullable=True),
    sa.Column('delivery_liter', sa.String(length=50), nullable=True),
    sa.Column('delivery_marketplace_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_marketplace_coef', sa.String(length=50), nullable=True),
    sa.Column('delivery_marketplace_liter', sa.String(length=50), nullable=True),
    sa.Column('storage_base', sa.String(length=50), nullable=True),
    sa.Column('storage_coef', sa.String(length=50), nullable=True),
    sa.Column('storage_liter', sa.String(length=50), nullable=True),
    sa.Column('tariff_date', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_name', name='uq_tariff_box')
    )
    op.create_index(op.f('ix_tariff_boxes_warehouse_name'), 'tariff_boxes', ['warehouse_name'], unique=False)
    op.create_table('tariff_pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_expr', sa.String(length=50), nullable=True),
    sa.Column('delivery_value_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_value_liter', sa.String(length=50), nullable=True),
    sa.Column('storage_expr', sa.String(length=50), nullable=True),
    sa.Column('storage_value', sa.String(length=50), nullable=True),
    sa.Column('tariff_date', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_name', name='uq_tariff_pallet')
    )
    op.create_index(op.f('ix_tariff_pallets_warehouse_name'), 'tariff_pallets', ['warehouse_name'], unique=False)
    op.create_table('tariff_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_dump_kgt_office_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_kgt_office_liter', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_kgt_return', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_srg_office', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_srg_return', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_sup_courier_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_sup_courier_liter', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_sup_office_base', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_sup_office_liter', sa.String(length=50), nullable=True),
    sa.Column('delivery_dump_sup_return', sa.String(length=50), nullable=True),
    sa.Column('tariff_date', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_name', name='uq_tariff_return')
    )
    op.create_index(op.f('ix_tariff_returns_warehouse_name'), 'tariff_returns', ['warehouse_name'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('cargo_type', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.Integer(), nullable=False),
    sa.Column('federal_district', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_office_id'), 'warehouses', ['office_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_office_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_tariff_returns_warehouse_name'), table_name='tariff_returns')
    op.drop_table('tariff_returns')
    op.drop_index(op.f('ix_tariff_pallets_warehouse_name'), table_name='tariff_pallets')
    op.drop_table('tariff_pallets')
    op.drop_index(op.f('ix_tariff_boxes_warehouse_name'), table_name='tariff_boxes')
    op.drop_table('tariff_boxes')
    op.drop_index(op.f('ix_tariff_acceptances_warehouse_id'), table_name='tariff_acceptances')
    op.drop_table('tariff_acceptances')
    op.drop_index(op.f('ix_claims_srid'), table_name='claims')
    op.drop_index(op.f('ix_claims_nm_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_cabinet_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
