"""recreate_analytics_for_v3_sales_funnel

Revision ID: eb7bdbb26cde
Revises: b9bef58c9f87
Create Date: 2026-06-13 19:57:44.734366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7bdbb26cde'
down_revision: Union[str, Sequence[str], None] = 'b9bef58c9f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_metrics', sa.Column('open_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('cart_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('order_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('order_sum', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('buyout_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('buyout_sum', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_add_to_cart', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_cart_to_order', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_buyout', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_open_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_cart_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_order_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_order_sum', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_buyout_count', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('past_conv_buyout', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('dynamic_open', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('dynamic_cart', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('dynamic_order', sa.Integer(), nullable=False))
    op.add_column('funnel_metrics', sa.Column('dynamic_buyout', sa.Integer(), nullable=False))
    op.drop_column('funnel_metrics', 'conv_cart_order')
    op.drop_column('funnel_metrics', 'avg_orders_month1')
    op.drop_column('funnel_metrics', 'avg_orders')
    op.drop_column('funnel_metrics', 'sale_rate_days')
    op.drop_column('funnel_metrics', 'availability')
    op.drop_column('funnel_metrics', 'conv_order_buyout')
    op.drop_column('funnel_metrics', 'avg_orders_month2')
    op.drop_column('funnel_metrics', 'buyout_percent')
    op.drop_column('funnel_metrics', 'stock_turnover_days')
    op.add_column('shelf_metrics', sa.Column('product_rating', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('feedback_rating', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('open_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('cart_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('order_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('order_sum', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('cancel_count', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('cancel_sum', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('avg_price', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('avg_orders_per_day', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('share_order_percent', sa.Float(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('add_to_wishlist', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('conv_add_to_cart', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('conv_cart_to_order', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('conv_buyout', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('stocks_wb', sa.Integer(), nullable=False))
    op.add_column('shelf_metrics', sa.Column('stocks_mp', sa.Integer(), nullable=False))
    op.alter_column('shelf_metrics', 'buyout_sum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('shelf_metrics', 'orders_sum')
    op.drop_column('shelf_metrics', 'main_photo')
    op.drop_column('shelf_metrics', 'avg_orders')
    op.drop_column('shelf_metrics', 'sale_rate_days')
    op.drop_column('shelf_metrics', 'stock_count')
    op.drop_column('shelf_metrics', 'lost_orders_count')
    op.drop_column('shelf_metrics', 'availability')
    op.drop_column('shelf_metrics', 'lost_buyouts_sum')
    op.drop_column('shelf_metrics', 'stock_sum')
    op.drop_column('shelf_metrics', 'orders_count')
    op.drop_column('shelf_metrics', 'lost_orders_sum')
    op.drop_column('shelf_metrics', 'from_client_count')
    op.drop_column('shelf_metrics', 'lost_buyouts_count')
    op.drop_column('shelf_metrics', 'to_client_count')
    op.drop_column('shelf_metrics', 'buyout_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelf_metrics', sa.Column('buyout_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('to_client_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_buyouts_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('from_client_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_orders_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('orders_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('stock_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('lost_buyouts_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('availability', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('lost_orders_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('stock_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('sale_rate_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('avg_orders', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shelf_metrics', sa.Column('main_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shelf_metrics', sa.Column('orders_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('shelf_metrics', 'buyout_sum',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('shelf_metrics', 'stocks_mp')
    op.drop_column('shelf_metrics', 'stocks_wb')
    op.drop_column('shelf_metrics', 'conv_buyout')
    op.drop_column('shelf_metrics', 'conv_cart_to_order')
    op.drop_column('shelf_metrics', 'conv_add_to_cart')
    op.drop_column('shelf_metrics', 'add_to_wishlist')
    op.drop_column('shelf_metrics', 'share_order_percent')
    op.drop_column('shelf_metrics', 'avg_orders_per_day')
    op.drop_column('shelf_metrics', 'avg_price')
    op.drop_column('shelf_metrics', 'cancel_sum')
    op.drop_column('shelf_metrics', 'cancel_count')
    op.drop_column('shelf_metrics', 'order_sum')
    op.drop_column('shelf_metrics', 'order_count')
    op.drop_column('shelf_metrics', 'cart_count')
    op.drop_column('shelf_metrics', 'open_count')
    op.drop_column('shelf_metrics', 'feedback_rating')
    op.drop_column('shelf_metrics', 'product_rating')
    op.add_column('funnel_metrics', sa.Column('stock_turnover_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('buyout_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('avg_orders_month2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_order_buyout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('availability', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('funnel_metrics', sa.Column('sale_rate_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('avg_orders', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('avg_orders_month1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('funnel_metrics', sa.Column('conv_cart_order', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('funnel_metrics', 'dynamic_buyout')
    op.drop_column('funnel_metrics', 'dynamic_order')
    op.drop_column('funnel_metrics', 'dynamic_cart')
    op.drop_column('funnel_metrics', 'dynamic_open')
    op.drop_column('funnel_metrics', 'past_conv_buyout')
    op.drop_column('funnel_metrics', 'past_buyout_count')
    op.drop_column('funnel_metrics', 'past_order_sum')
    op.drop_column('funnel_metrics', 'past_order_count')
    op.drop_column('funnel_metrics', 'past_cart_count')
    op.drop_column('funnel_metrics', 'past_open_count')
    op.drop_column('funnel_metrics', 'conv_buyout')
    op.drop_column('funnel_metrics', 'conv_cart_to_order')
    op.drop_column('funnel_metrics', 'conv_add_to_cart')
    op.drop_column('funnel_metrics', 'buyout_sum')
    op.drop_column('funnel_metrics', 'buyout_count')
    op.drop_column('funnel_metrics', 'order_sum')
    op.drop_column('funnel_metrics', 'order_count')
    op.drop_column('funnel_metrics', 'cart_count')
    op.drop_column('funnel_metrics', 'open_count')
    # ### end Alembic commands ###
